### ISSUE TITLE
Graphite returning 500 for some urls

### ISSUE THREAD

**Issue by paladox** [wikimedia/nagf#20]
Hi, when going to https://tools.wmflabs.org/nagf/?project=tools it shows 500 (alot of them) for grafana for urls like https://graphite-labs.wikimedia.org/render/?title=tools-worker-1017.tools.eqiad.wmflabs+Memory+last+day&width=800&height=250&from=-1day&hideLegend=false&uniqueLegend=true&target=alias%28color%28stacked%28diffSeries%28tools.tools-worker-1017.tools.eqiad.wmflabs.memory.MemTotal%2Ctools.tools-worker-1017.tools.eqiad.wmflabs.memory.%7BMemFree%2CBuffers%2CCached%7D%29%29%2C%22%235555cc%22%29%2C%22Used%22%29&target=alias%28color%28stacked%28tools.tools-worker-1017.tools.eqiad.wmflabs.memory.Cached%29%2C%22%2333cc33%22%29%2C%22Cached%22%29&target=alias%28color%28stacked%28tools.tools-worker-1017.tools.eqiad.wmflabs.memory.Buffers%29%2C%22%2399ff33%22%29%2C%22Buffers%22%29&target=alias%28alpha%28color%28stacked%28tools.tools-worker-1017.tools.eqiad.wmflabs.memory.MemFree%29%2C%22%23f0ffc0%22%29%2C0.4%29%2C%22Free%22%29&target=alias%28color%28stacked%28tools.tools-worker-1017.tools.eqiad.wmflabs.memory.SwapCached%29%2C%22%239900CC%22%29%2C%22Swap%22%29&target=alias%28color%28tools.tools-worker-1017.tools.eqiad.wmflabs.memory.MemTotal%2C%22red%22%29%2C%22Total%22%29

But @zhuyifei1999 has a old fork https://tools.wmflabs.org/yifeibot/nagf/?project=tools which works, so some how the latest version is broken with graphite

**Comment by paladox** [comment]
@Krinkle it's been showing this

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/graphite/render/views.py", line 110, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 28, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 28, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 28, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 29, in evaluateTokens
    return func(requestContext, *args)
  File "/usr/lib/python2.7/dist-packages/graphite/render/functions.py", line 247, in diffSeries
    (seriesList,start,end,step) = normalize(seriesLists)
  File "/usr/lib/python2.7/dist-packages/graphite/render/functions.py", line 120, in normalize
    step = reduce(lcm,[s.step for s in seriesList])
TypeError: reduce() of empty sequence with no initial value

```
all day for me

**Comment by paladox** [comment]
I filed this https://phabricator.wikimedia.org/T198209 too.

**Comment by paladox** [comment]
@Krinkle does all the images load on https://tools.wmflabs.org/nagf/?project=tools for you? or just the ones at the top?

**Comment by Krinkle** [comment]
As I said, they sometimes fail. This isn't related to Nagf.

**Comment by paladox** [comment]
But it hasn't work for me though. Yes it may sometimes, but it hasen't worked for me at all today whereas https://tools.wmflabs.org/yifeibot/nagf/?project=tools does which indicates there's a bug in nagf. Since if this works https://tools.wmflabs.org/yifeibot/nagf/?project=tools works and this https://tools.wmflabs.org/nagf/?project=tools  doesn't.

**Comment by Krinkle** [comment]
@paladox I've cleared the cache and restarted Nagf. The errors seem to happen less often now. Not sure what the issue was.
